facelessuser/Rummage

docs/src/markdown/changelog.md, rummage/__main__.py, rummage/lib/__version__.py, rummage/lib/gui/actions/fileops.py, rummage/lib/gui/actions/open_editor.py, rummage/lib/gui/app/custom_app.py, rummage/lib/gui/controls/custom_statusbar.py, rummage/lib/gui/controls/dynamic_lists.py, rummage/lib/gui/controls/result_lists.py, rummage/lib/gui/rummage_dialog.py, rummage/lib/util/__init__.py, rummage/lib/util/win_subprocess.py, tox.ini
- Add context menu to "File" tab with "Reveal in File Manager" item.
- Fix Unicode input issues on Windows.
- Fix Unicode shell subprocessor path issues (ugly, but it works).
=> File context menu and Windows Unicode fix

docs/src/markdown/changelog.md, rummage/lib/gui/notify/__init__.py, rummage/lib/gui/rummage_dialog.py
=> Fix missing play_alert

rummage/lib/gui/app/custom_app.py, rummage/lib/gui/controls/result_lists.py
=> Add content context menu and limit bulk open to 20

rummage/lib/gui/app/custom_app.py, rummage/lib/gui/controls/custom_statusbar.py, rummage/lib/gui/controls/dynamic_lists.py, rummage/lib/gui/controls/result_lists.py, rummage/lib/gui/rummage_dialog.py
Ref #165. Also fix issue where log entries were displayed even if they were not at the proper log level.  Also fix some "leaky" objects: status icons cleanup on close, cleanup context menus, and adjust timer cleanup on close.
=> Copy records

.dictionary, docs/src/markdown/changelog.md, docs/src/markdown/usage.md, requirements/project.txt, requirements/test-project.txt, rummage/lib/__version__.py, setup.py
Update version, docs, and changelog to prepare for a new release. Requirements should be sourced directly from the requirments file. We should also build a version specific CLI app as well in case we have multiple Python versions. Require backrefs 3.0.3.
=> Update changelog, docs, and setup

.dictionary, docs/src/markdown/usage.md
=> Document update issue

docs/src/markdown/usage.md
Document how to include icons in Windows contet menu entry. Ref #203
=> Update documentation on context menu

docs/src/markdown/changelog.md, rummage/lib/rumcore/__init__.py
Lines are calculated incrementally as needed opposed to all up front.
=> incremental-line-endings

docs/src/markdown/changelog.md, requirements/project.txt, requirements/test-project.txt, rummage/lib/__version__.py, rummage/lib/gui/regex_test_dialog.py
Ref #212. Also require backrefs 3.3.0.
=> Fix test dialog bug

docs/src/markdown/changelog.md, rummage/lib/__version__.py, rummage/lib/gui/notify/notify_windows.py
Don't use callbacks to hide taskbar icon, just remove it as soon as notification is issued.
https://github.com/facelessuser/SubNotify/issues/7
=> Window notify tweaks

docs/src/markdown/changelog.md, rummage/lib/__version__.py, rummage/lib/gui/rummage_dialog.py
=> Escape key

gui.fbp, rummage/lib/gui/gui.py, rummage/lib/gui/import_settings_dialog.py, rummage/lib/gui/rummage_dialog.py, rummage/lib/gui/settings/__init__.py, rummage/lib/gui/settings_dialog.py, rummage/lib/rumcore/__init__.py
=> Remove rawchars flag in favour of case flag

rummage/lib/rumcore/__init__.py
=> Respect regex ver in file patterns

docs/src/markdown/changelog.md, requirements/project.txt, requirements/test-project.txt, rummage/lib/__version__.py, rummage/lib/rumcore/__init__.py
=> Prep for 4.1.2

.travis.yml, docs/src/markdown/changelog.md, rummage/lib/__version__.py, setup.py, tox.ini
=> python3.7 support

docs/src/markdown/changelog.md, rummage/lib/gui/controls/dynamic_lists.py, rummage/lib/gui/controls/result_lists.py, rummage/lib/gui/import_settings_dialog.py, rummage/lib/gui/rummage_dialog.py, rummage/lib/gui/settings/__init__.py
=> Add the ability to hide columns

rummage/lib/gui/controls/result_lists.py
=> Windows requires checked item 'in' the menu to check

docs/src/markdown/changelog.md, gui.fbp, rummage/lib/__version__.py, rummage/lib/gui/gui.py, rummage/lib/gui/rummage_dialog.py
=> Better default search tab input focus

docs/src/markdown/changelog.md, rummage/lib/__version__.py, rummage/lib/gui/rummage_dialog.py, rummage/lib/gui/settings_dialog.py
=> Fix multi update notification issue

docs/src/markdown/changelog.md, mkdocs.yml, requirements/project.txt, requirements/test-project.txt, rummage/lib/__version__.py, rummage/lib/gui/regex_test_dialog.py, tests/spellcheck.py
=> Process preview even when replace pattern is empty

LICENSE.md
Reformat [LICENSE.md](LICENSE.md) to make it recognized by GitHub
=> Reformat LICENSE

requirements/test-project.txt
=> Test using latest backrefs

appveyor.yml, requirements/project.txt, requirements/test-project.txt, tox.ini
=> Require latest backrefs to prevent install issues.

gui.fbp, rummage/lib/gui/controls/collapsible_pane.py, rummage/lib/gui/gui.py, rummage/lib/gui/rummage_dialog.py, rummage/lib/gui/settings_dialog.py, rummage/lib/util/__init__.py
Fixes for platform specific quirks in tab panel backgrounds.
=> Tab panel background fixes

docs/src/markdown/changelog.md, rummage/lib/__meta__.py, rummage/lib/gui/data/docs/.dochash, rummage/lib/gui/data/docs/changelog.html, rummage/lib/gui/data/docs/extras.html, rummage/lib/gui/notify/__init__.py, rummage/lib/gui/notify/notify_linux.py, rummage/lib/gui/notify/notify_osx.py, rummage/lib/gui/notify/notify_windows.py
=> Ignore errors with notification audio alerts

docs/src/markdown/changelog.md, rummage/lib/gui/controls/custom_statusbar.py, rummage/lib/gui/controls/result_lists.py, rummage/lib/gui/data/docs/.dochash, rummage/lib/gui/data/docs/changelog.html
=> Clear timed status when mouse leaves result item and decrease time

gui.fbp, rummage/lib/gui/controls/dynamic_lists.py, rummage/lib/gui/dialogs/import_settings_dialog.py, rummage/lib/gui/dialogs/rummage_dialog.py, rummage/lib/gui/dialogs/settings_dialog.py, rummage/lib/gui/gui.py, rummage/lib/gui/settings/__init__.py
=> Add option to turn off alternating row colors in lists

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/labels.yml, .github/workflows/pullrequest.yml, .travis.yml, README.md, tools/gh_labels.py, tools/labels.json, tox.ini
Rename master and pull to build.yml and pullrequest.yml
Add travis config to test Py38
=> Workflow and test changes

rummage/lib/__meta__.py, rummage/lib/gui/app/custom_app.py
=> Fix debug not working on latest wxpython

requirements/project.txt
=> Require wcmatch 6.1
