facelessuser/Rummage

- .travis.yml
- requirements/lint.txt
- rummage/lib/__version__.py
- rummage/lib/gui/actions/export_html.py
- rummage/lib/gui/app/custom_app.py
- rummage/lib/gui/settings/__init__.py
- rummage/lib/util/__init__.py
- rummage/lib/util/win_subprocess.py
- tox.ini
Ditch flake8-putty which is locked to <2.  It is mainly used to ignore naming issues with wxpython, but I don't have an issue with accidentally messing up naming conventions, and I can easily catch those kinds of issues in pull requests via a review.  Other issues were fixes that we ignored due to lazyness. Also, now we will run flake8 on Python3 instead of 2.  I want to prepare for when PY2 is no longer supported in 2020 as we will most likely drop PY2 support then ourselves.
> Move to flake8 3.0

- docs/src/markdown/installation.md
Fedora need 
* gcc-c++ 
* wxGTK-devel 
* gstreamer-devel
* webkitgtk-devel 
* GConf2-devel 
* gstreamer-plugins-base-devel
as dependencies to build wxPython during installation
> Add instruction for Fedora linux users

- rummage/lib/gui/controls/custom_statusbar.py
Set an upper bound on when to apply monkey patch to supertooltip.  Also, if desired line is not found, don'tattempt to replace.
> Don't always apply supertooltip patch

- gui.fbp
- rummage/lib/gui/gui.py
- rummage/lib/gui/rummage_dialog.py
- rummage/lib/util/__init__.py
Generate the encoding list on startup for the given Python.  Sort them (treating numbers as actual numbers during sort) and add them to the choice control.
> Auto encoding gen

- .dictionary
- docs/src/markdown/changelog.md
- docs/src/markdown/installation.md
- docs/src/markdown/usage.md
- gui.fbp
- requirements/project.txt
- requirements/test-project.txt
- rummage/__main__.py
- rummage/lib/gui/controls/dynamic_lists.py
- rummage/lib/gui/controls/result_lists.py
- rummage/lib/gui/gui.py
- rummage/lib/gui/regex_test_dialog.py
- rummage/lib/gui/rummage_dialog.py
- rummage/lib/rumcore/__init__.py
- rummage/lib/safe_import.py
- rummage/lib/util/__init__.py
- setup.py
- tests/test_rumcore.py
- **NEW**: Add extension column in results.
- **NEW**: Status now just shows `[ACTIVE]` or `[DONE]` instead of a misleading percentage.
- **NEW**: Can now multi-select and mass open files in your editor.
- **NEW**: Better error feedback in regex tester.
- **NEW**: Remove current directory from Python path when opening Rummage to prevent it from importing local libraries when launched inside a Python project.  This mainly affects `python -m rummage` and `pythonw -m rummage` launching.
- **FIX**: Result item hover not showing file name in status bar.
- **FIX**: Warnings in plugin system.
> New features etc. for 3.4.0

- docs/src/markdown/changelog.md
- rummage/lib/gui/regex_test_dialog.py
- rummage/lib/gui/rummage_dialog.py
- rummage/lib/rumcore/__init__.py
Turns out testing sub was nowhere near sufficient  to understand reverse.  regex.REVERSE literally returns all the matches in reverse order, especially when it is iteratting. Fix behavior in core and in test dialog.
Finally tested without regex installed.  This should be squashed for sure this time.
> Fix reverse search, fix bregex import error

- rummage/lib/gui/controls/result_lists.py
When sorting in the content tab, for secondary sort, file name has secondary priority, but give line number third.
> Prioritize line column

- .dictionary
- docs/src/markdown/_snippets/links.md
- docs/src/markdown/changelog.md
- docs/src/markdown/usage.md
- rummage/lib/rumcore/__init__.py
- rummage/lib/util/__init__.py
- tests/test_rumcore.py
Handle pattern separators properly and allow character notations for things like \xXX or \uXXXX etc. Fix documentation in regards to wildcard patterns and better explain what the wildcard rules are.
Ref #193
> Rework wildcard patterns

- rummage/lib/rumcore/__init__.py
- tests/test_rumcore.py
Escape `&|~-` because future Python versions will handle these differently.  Handle hypens properly as they can also be range delimiters.
> Better wildcard handling

- docs/src/markdown/usage.md
- rummage/lib/rumcore/__init__.py
- tests/test_rumcore.py
More wildcard considerations.  Ensure backslash does not consume special wildcard characters. Ensure we handle escaped backslashes properly: `\\`.
> Wildcard escape considerations

- docs/src/markdown/changelog.md
- gui.fbp
- rummage/lib/gui/controls/dynamic_lists.py
- rummage/lib/gui/controls/encoding_list.py
- rummage/lib/gui/controls/load_search_list.py
- rummage/lib/gui/controls/result_lists.py
- rummage/lib/gui/controls/search_chain_list.py
- rummage/lib/gui/controls/search_error_list.py
- rummage/lib/gui/gui.py
- rummage/lib/gui/load_search_dialog.py
- rummage/lib/gui/rummage_dialog.py
- rummage/lib/gui/search_chain_dialog.py
- rummage/lib/gui/search_error_dialog.py
- rummage/lib/gui/settings_dialog.py
Cleanup ClientDC objects. 
Also wasn't aware, but image list needs to get cleaned up, so use AssignImageList to prevent leaking objects as it should auto clean up.
Unrelated, fix for chain dialog not being sized correctly
> Cleanup objects

- docs/src/markdown/changelog.md
- rummage/lib/__version__.py
- rummage/lib/gui/actions/updates.py
- rummage/lib/gui/localization/locale/en_US/LC_MESSAGES/rummage.po
- rummage/lib/gui/localization/locale/ru_RU/LC_MESSAGES/rummage.po
- rummage/lib/gui/localization/locale/rummage.pot
- rummage/lib/gui/rummage_dialog.py
Regenerate out of date localization. Log error during update check. If not a silent check, alert user there was an update check issue. Also use https for requests when checking updates.
> Fixes to updates and localization

- .dictionary
- .travis.yml
- docs/src/markdown/installation.md
- docs/src/markdown/usage.md
Update documentation to cover KDE menu adding. Clarify some wxPython installation things and stress that wxPython issues should be taken up with the wxPython repo (I don't have time to investigate  different distros installation requirements).
> prep 4.2.1

- docs/src/markdown/changelog.md
- requirements/project.txt
- requirements/test-project.txt
- rummage/lib/__version__.py
- rummage/lib/rumcore/__init__.py
Use the appropriate flags as the flags changed for 2.0. We'll use the short form which actually work for pre 2.0 version as well. Ref #271
> Make adjustments for wcmatch 2.0

- rummage/lib/rumcore/__init__.py
We don't need to "kill" DirWalker. We can use a simple break.
Originally, before we split out the logic into wcmatch, we were using
this class differently. There really is no reason to kill it as it
shouldn't have anything we want to process when we see the abort.
Additionally, in the future, I will remove the "kill" nonsense from the
WcMatch class.
> No need to "kill" DirWalker

- rummage/lib/gui/controls/autocomplete_combo.py
- rummage/lib/gui/rummage_dialog.py
When automcomplete lists are empty, and the last loaded entry is
requested, load an empty string. Also, handle swapping of chain and
normal search functionality better.
> Rework loading of autocomplete control loading

- rummage/lib/gui/dialogs/rummage_dialog.py
- rummage/lib/gui/dialogs/settings_dialog.py
Linux should not use the page background to paint the tab control and
collapsible controls, but instead should use the tab control. Colors are
not always reported exactly as they actually appear, so we will acquire
the default panel color in Linux and just use it for the tabbed
interface.
> Linux tab interface color fix

- rummage/lib/gui/controls/webview.py
- rummage/lib/gui/dialogs/checksum_dialog.py
- rummage/lib/gui/dialogs/column_dialog.py
- rummage/lib/gui/dialogs/delete_dialog.py
- rummage/lib/gui/dialogs/edit_search_chain_dialog.py
- rummage/lib/gui/dialogs/error_text_dialog.py
- rummage/lib/gui/dialogs/export_settings_dialog.py
- rummage/lib/gui/dialogs/file_ext_dialog.py
- rummage/lib/gui/dialogs/html_dialog.py
- rummage/lib/gui/dialogs/import_settings_dialog.py
- rummage/lib/gui/dialogs/load_search_dialog.py
- rummage/lib/gui/dialogs/overwrite_dialog.py
- rummage/lib/gui/dialogs/regex_test_dialog.py
- rummage/lib/gui/dialogs/rummage_dialog.py
- rummage/lib/gui/dialogs/save_search_dialog.py
- rummage/lib/gui/dialogs/search_chain_dialog.py
- rummage/lib/gui/dialogs/search_error_dialog.py
- rummage/lib/gui/dialogs/settings_dialog.py
- rummage/lib/gui/dialogs/support_info_dialog.py
Linux, when dealing with a tabbed interface, won't resize and refresh
controls correctly until after the window is loaded, so create an
on_loaded event for the preference window, and force a proper resize
then, but only for Linux.
> Ensure preferences is sized correctly on Linux

- rummage/lib/gui/app/rummage_app.py
- rummage/lib/gui/dialogs/rummage_dialog.py
Don't use the macOS dock technique to get the proper Windows taskbar
icon, but set the windows app id so the current frame icon will now
be used.
Closes #397
> Fix windows taskbar with a windows specific approach

- rummage/lib/gui/controls/dynamic_lists.py
The square where the horz and vert scrollbar meet becomes white on macOS
if background gets set (to any color). Just read the color and calculate
the alt list color, no need to set background to wx.NullColour.
> Setting background color of ListCtrl on macOS causes white scroll square
